# Questo workflow esegue la build e i test ad ogni push su qualsiasi branch.
name: Build e Test

on:
  push:
    branches:
      - '**' # Si attiva su tutti i branch

jobs:
  build_and_test:
    name: Build, Lint and Test
    uses: ./.github/workflows/reusable-build.yml
