# This workflow will publish a package to npm when a release is created
name: Publish to npm

on:
  release:
    types: [created]

jobs:
  # Chiama il workflow riutilizzabile per assicurarsi che il codice sia valido e per creare l'artefatto
  build_and_test:
    uses: ./.github/workflows/reusable-build.yml

  # Una volta che l'artefatto è pronto, procedi alla pubblicazione
  publish-npm:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for publishing
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org/

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: library-package # Nome dell'artefatto caricato dal job precedente

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
