# Questo workflow pubblica un pacchetto su npm quando viene creata una release.
name: Publish to npm

on:
  release:
    types: [created]

permissions:
  actions: read # Obbligatorio per actions/download-artifact

jobs:
  # Chiama il workflow riutilizzabile per costruire ed eseguire i test
  build_and_test:
    uses: ./.github/workflows/reusable-build.yml

  # Pubblicazione su npm
  publish-npm:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for publishing
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Usa la versione LTS più recente
          registry-url: https://registry.npmjs.org/

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: library-package # Nome dell'artefatto caricato dal job precedente
          path: package-dist # Scarica in una directory dedicata

      - name: Publish to npm
        run: |
          if [[ "${{ github.event.release.tag_name }}" == *"beta"* ]]; then
            npm publish --tag beta
          else
            npm publish
          fi
        working-directory: ./package-dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
